<?php

/**
 * @file
 * IISP profiler main module.
 */

/**
 * @defgroup action_example Example: Action
 * @ingroup examples
 * @{
 * Creating actions in Drupal 7
 *
 */


/**
 * Implements hook_menu().
 *
 * Provides a menu entry which explains what the module does.
 */
 
function iisp_profiler_init(){
	global $base_url;
	$path = drupal_get_path('module', 'iisp_profiler');
	
	drupal_add_css($base_url . '/' . $path . '/css/custom-style.css', array('type' => 'external', 'weight' => '500'));
}
 
function iisp_profiler_menu() {
  
  $items['admin/iisp_profiler/skills/view'] = array(
    'title' => 'Skills',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
  
  $items['admin/iisp_profiler/skills/categories'] = array(
    'title'           => 'Skills categories',
    'description'     => 'Provides the skills categories for the iisp profiler',
    'page callback'   => 'iisp_skills_categories',
	'type' 			  => MENU_LOCAL_TASK,
    'file'            => 'admin/profiler_admin.inc', 
	'access arguments' => array('administer skill profiler settings'),
  );
 
  $items['admin/iisp_profiler/skills/categories/create'] = array(
    'title'           => 'create new skills categories',
    'description'     => 'Provides the skills categories for the iisp profiler',
    'page callback'   => 'iisp_skills_categories',
    'page arguments' => array('create'),
    'file'            => 'admin/profiler_admin.inc',
	'type' => MENU_CALLBACK,
    'access arguments' => array('administer skill profiler settings'),
  );
  
  $items['admin/iisp_profiler/skills/categories/%/edit'] = array(
    'title'           => 'Edit skills categories',
    'description'     => 'Provides the skills categories for the iisp profiler',
    'page callback'   => 'iisp_skills_categories_page_edit',
    'page arguments'  => array(4), 
    'file'            => 'admin/profiler_admin.inc', 
	'type' => MENU_CALLBACK,
    'access arguments' => array('administer skill profiler settings'),
  );

  $items['admin/iisp_profiler/skills'] = array(
    'title'           => 'Skills groups',
    'description'     => 'Provides the  skills for the  profiler',
    'page callback'   => 'iisp_skills_skills',
	'file'            => 'admin/profiler_admin_skills.inc', 
    'access arguments' => array('administer skill profiler settings'),
	'type' => MENU_LOCAL_TASK,
	'weight' => -10,
  );
  

  $items['admin/iisp_profiler/skills/create'] = array(
    'title'           => 'Create IISP skills',
    'description'     => 'Provides the iisp skills for the iisp profiler',
    'page callback'   => 'iisp_skills_skills',
	'page arguments'  => array('create'),
	'file'            => 'admin/profiler_admin_skills.inc',
	'type' => MENU_CALLBACK, 
    'access arguments' => array('administer skill profiler settings'),
  );
  
  $items['admin/iisp_profiler/skills/%/edit'] = array(
    'title'           => 'Edit skills',
    'description'     => 'Provides the  skills for the  profiler',
    'file'            => 'admin/profiler_admin.inc', 
    'page callback'   => 'iisp_skills_skills_page_edit',
	'page arguments'  => array(3),
	'file'            => 'admin/profiler_admin_skills.inc', 
	'type' => MENU_CALLBACK,
    'access arguments' => array('administer skill profiler settings'),
  );
  
  $items['admin/iisp_profiler/config'] = array(
    'title'           => 'Skills Admin configuraton',
    'description'     => 'Provides the admin configuration for the profiler',
    'page callback'   => 'drupal_get_form',
	'page arguments'  => array('iisp_admin_config_form'),
    'file'            => 'admin/iisp_config.inc', 
    'access arguments' => array('administer skill profiler settings'),
	'type' => MENU_LOCAL_TASK,
  );
  
  $items['admin/iisp_profiler/field_settings'] = array(
    'title'           => t('Field settings'),
    'description'     => t('Provides the fields settings for the iisp profiler'),
    'page callback'   => 'iisp_fields_settings',
    'file'            => 'admin/field_settings.inc', 
    'access arguments' => array('administer skill profiler settings'),
	'type' => MENU_LOCAL_TASK,
  );

  $items['admin/iisp_profiler/field_settings/create'] = array(
      'title' => t('Create field settings'),
      'description' => t('Create the fields settings for the profiler'),
      'page callback' => 'iisp_fields_settings',
      'page arguments' => array('create'),
      'file' => 'admin/field_settings.inc',
	    'type' => MENU_CALLBACK,
      'access arguments' => array('administer skill profiler settings'),
  );


  $items['admin/iisp_profiler/field_settings/%/edit'] = array(
      'title' => t('Edit field settings'),
      'description' => t('Edit the fields settings for the profiler'),
      'page callback' => 'iisp_fields_settings_page_edit',
      'page arguments' => array(3),
      'access arguments' => array('administer skill profiler settings'),
	    'type' => MENU_CALLBACK,
      'file' => 'admin/field_settings.inc',
      'weight' => 1,
  );

  $items['admin/iisp_profiler/sifa_skills_types'] = array(
    'title'           => 'Role family',
    'description'     => 'Provides the Role families',
    'page callback'   => 'sifa_skill_types',
	'file'            => 'admin/sifa_skill_types_settings.inc', 
    'access arguments' => array('administer skill profiler settings'),
	'type' => MENU_LOCAL_TASK,
  );

  $items['admin/iisp_profiler/sifa_skills_levels'] = array(
    'title'           => 'Skills levels',
    'description'     => 'Provides the skills levels',
    'page callback'   => 'sifa_skill_levels',
    'file'            => 'admin/sifa_skill_levels_settings.inc', 
    'access arguments' => array('administer skill profiler settings'),
	'type' => MENU_LOCAL_TASK,
  );
 
  
  $items['iisp_profiler/settings'] = array(
    'title'           => 'Settings',
    'description'     => 'Provides the settings for the profiler',
    'page callback'   => 'iisp_profiler_settings',
	  'file'            => 'profiler_settings.inc', 
    'access arguments' => array('skill profiler works'),
  );
  
  $items['iisp_profiler/activities'] = array(
    'title'           => 'Activities',
    'description'     => 'Provides the activities for the iisp profiler',
    'page callback'   => 'iisp_profiler_activities',
    'file'            => 'profiler_activities.inc', 
	  'access arguments' => array('skill profiler works'),
  );
  
  $items['iisp_profiler/activities/create'] = array(
    'title'           => 'Add activities',
    'description'     => 'Add the activities for the iisp profiler',
    'page callback'   => 'iisp_profiler_activities',
	  'page arguments'  => array('create'),
    'file'            => 'profiler_activities.inc', 
	  'access arguments' => array('skill profiler works'),
  );
  
  $items['iisp_profiler/activities/%/edit'] = array(
    'title'           => 'Edit activities',
    'description'     => 'Edit activities for the iisp profiler',
    'page callback'   => 'iisp_profiler_activities_page_edit',
	  'page arguments'  => array(2),
    'file'            => 'profiler_activities.inc', 
	  'access arguments' => array('skill profiler works'),
  );
  
  $items['iisp_profiler/goals'] = array(
    'title'           => 'Goals',
    'description'     => 'Provides the goals for the iisp profiler',
    'page callback'   => 'iisp_profiler_activities',
    'file'            => 'profiler_goals.inc', 
	  'access arguments' => array('skill profiler works'),
  );
  $items['iisp_profiler/goals/create'] = array(
    'title'           => 'Add Goals',
    'description'     => 'Add the goals for the iisp profiler',
    'page callback'   => 'iisp_profiler_activities',
	  'page arguments'  => array('create'),
    'file'            => 'profiler_goals.inc', 
	  'access arguments' => array('skill profiler works'),
  );
  
  
  $items['iisp_profiler/goals/%/edit'] = array(
    'title'           => 'Edit Goals',
    'description'     => 'Edit goals for the iisp profiler',
    'page callback'   => 'iisp_profiler_activities_page_edit',
	  'page arguments'  => array(2),
    'file'            => 'profiler_goals.inc', 
	  'access arguments' => array('skill profiler works'),
  );
  
  
  $items['iisp_profiler/profiles'] = array(
    'title'           => 'Profiles',
    'description'     => 'Provides the profiles for the iisp profiler',
    'page callback'   => 'iisp_profiler',
    'file'            => 'profiler_info.inc',
    'access arguments' => array('skill profiler works'),
  );

  $items['iisp_profiler/profiles/create'] = array(
    'title'           => 'Profiles',
    'description'     => 'Create new profiles for the iisp profiler',
    'page callback'   => 'iisp_profiler',
	  'page arguments' => array('create'),
    'file'            => 'profiler_info.inc',
	  'access arguments' => array('skill profiler works'),
  );
  
  
  $items['iisp_profiler/dashboard'] = array(
    'title'           => 'Dashboard',
    'description'     => 'Provides the dashboard for the iisp profiler',
    'page callback'   => 'iisp_profiler_dashboard',
    'file'            => 'profiler_dashboard.inc', 
	  'access arguments' => array('skill profiler works'),
  );
  
  $items['iisp_skills/ajax_settings'] = array(
    'title'           => 'Settings',
    'description'     => 'Provides the ajax callback settings for the iisp profiler',
    'page callback'   => 'ajax_settings',
    'file'            => 'profiler_settings.inc', 
	  'access arguments' => array('skill profiler works'),
  );
  
  $items['skills/receive_settings_data'] = array(
    'title'           => 'Receive settings data',
    'description'     => 'Receive settings data',
    'page callback'   => 'receive_settings_data',
    'file'            => 'profiler_settings.inc', 
	  'access arguments' => array('skill profiler works'),
  );
  
  $items['iisp_profiler/profiles/skill/%'] = array(
    'title'           => 'Profiles',
    'description'     => 'Provides the profiles for the iisp profiler',
    'page arguments'  => array(3),
    'page callback'   => 'iisp_profiler_skill_add',
    'file'            => 'profiler_info.inc',
    'access arguments' => array('skill profiler works'),
  );

  $items['iisp_skills/ajax_skills_profile'] = array(
    'title'           => 'Settings profile skills insert',
    'description'     => 'Provides the ajax callback settings for the iisp profiler skills',
    'page callback'   => 'ajax_skills_profile',
    'file'            => 'profiler_info.inc', 
    'access arguments' => array('skill profiler works'),
  );

  $items['iisp_skills/compare'] = array(
    'title'           => 'Compare profiles',
    'description'     => 'Compare profiles',
    'page callback'   => 'ajax_compare_profile',
    'file'            => 'profiler_info.inc', 
    'access arguments' => array('skill profiler works'),
  );

  $items['iisp_skills/ajax_skills_profile_data/%'] = array(
    'title'           => 'Settings profile skill data',
    'description'     => 'Provides settings for the iisp profiler skills',
    'page arguments'  => array(2),
    'page callback'   => 'ajax_skills_profile_data',
    'file'            => 'profiler_info.inc', 
    'access arguments' => array('skill profiler works'),
  );

  
  $items['iisp_skills/remove_skills_profile'] = array(
    'title'           => 'Remove settings profile skills insert',
    'description'     => 'Provides the ajax callback settings for removing iisp profiler skills',
    'page callback'   => 'remove_skills_profile',
    'file'            => 'profiler_info.inc', 
    'access arguments' => array('skill profiler works'),
  );

   $items['iisp_skills/ajax_set_share_link'] = array(
    'title'           => 'Settings profile share link insert',
    'description'     => 'Provides the ajax callback settings for share link of the profiler',
    'page callback'   => 'ajax_share_link_profile',
    'file'            => 'profiler_info.inc', 
    'access arguments' => array('skill profiler works'),
  );

   $items['iisp_skills/print/%'] = array(
    'title'           => 'Preview skills profiler page',
    'description'     => 'Preview skills profiler page',
    'page callback'   => 'print_iisp_profiles',
    'file'            => 'profiler_info.inc', 
    'page arguments'  => array(2),
    'access arguments' => array('skill profiler works'),
  );

   $items['iisp_skills/help'] = array(
    'title'           => 'Help of skill pages',
    'description'     => 'Help of skill pages',
    'page callback'   => 'help_iisp_profiles',
    'file'            => 'profiler_info.inc', 
    'access arguments' => array('skill profiler works'),
  );

   $items['iisp_skills/skills'] = array(
    'title'           => 'Skills',
    'description'     => 'Skills',
    'page callback'   => 'skills_iisp_profiles',
    'file'            => 'profiler_info.inc', 
    'access arguments' => array('skill profiler works'),
  );


  $items['iisp_skills/ajax_profile_name'] = array(
    'title'           => 'Get profile name from ajax',
    'description'     => 'Provides profile name from ajax',
    'page callback'   => 'ajax_skills_profile_name',
    'file'            => 'profiler_info.inc', 
    'access arguments' => array('skill profiler works'),
  );

  $items['iisp_profiler/profiles/%/edit'] = array(
    'title'           => 'Edit Profiles',
    'description'     => 'Provides the specific profile',
    'file'            => 'admin/profiler_admin.inc', 
    'page callback'   => 'profile_form_page_edit',
    'page arguments'  => array(2),
    'file'            => 'profiler_info.inc', 
    'access arguments' => array('skill profiler works'),
  );

  $items['iisp_skills/ajax_skills_category_total'] = array(
    'title'           => 'Get skill category total from ajax',
    'description'     => 'Provides skill category total from ajax',
    'page callback'   => 'ajax_skills_cat_total',
    'file'            => 'profiler_info.inc', 
    'access arguments' => array('skill profiler works'),
  );
  
  return $items;
  
}

/**
* Implements hook_block_info
*/
function iisp_profiler_block_info(){
	// This example comes from node.module.
  $blocks['top_menu_for'] = array(
    'info' => t('Top menu for iisp profiler information'),
    'cache' => DRUPAL_NO_CACHE,
  );
  
  return $blocks;
}


/**
* Implements hook_block_view
*/
function iisp_profiler_block_view($delta = ''){
	 $block = array();

  switch ($delta) {
    case 'top_menu_for':
      $block['subject'] = t('Top menu for iisp_profiler applicaton');
      $block['content'] = '<ul style="text-align:center; list-style:none;">
          <li>'.l('<i class="fa fa-home"></i> Dashboard', 'iisp_profiler/dashboard',  array('html'=>true,  'attributes' => array('class' => array('btn', 'btn-medium', 'btn-default')))).'</li>
          <li>'.l('<i class="fa fa-key"></i> Development Goals', 'iisp_profiler/goals',  array('html'=>true, 'attributes' => array('class' => array('btn', 'btn-medium', 'btn-default')))).'</li>
          <li>'.l('<i class="fa fa-archive"></i> Activities', 'iisp_profiler/activities',  array('html'=>true, 'attributes' => array('class' => array('btn', 'btn-medium', 'btn-default')))).'</li>
          <li>'.l('<i class="fa fa-user"></i> Profiler', 'iisp_profiler/profiles',  array('html'=>true, 'attributes' => array('class' => array('btn', 'btn-medium', 'btn-default')))).'</li>
          <li>'.l('<i class="fa fa-wrench"></i> Settings', 'iisp_profiler/settings',  array('html'=>true, 'attributes' => array('class' => array('btn', 'btn-medium', 'btn-default')))).'</li></ul><br/><br/>
		  ';
      break;
  }
  return $block;
 }

//Custom functions
function get_active_variable($act) {
   if($act == '1') {
       $active = "Yes";
   } else {
       $active = "No" ;
   }    

   return $active;
}

function get_keyvalue_array($keyvalue_unmanaged_arr){
  $options = array();
    $keyvalue_unmanaged_arr = preg_split("/\\r\\n|\\r|\\n/", $keyvalue_unmanaged_arr);
  foreach($keyvalue_unmanaged_arr as $kpr){
    $key_pair_separated = explode('|', $kpr);
    $options[$key_pair_separated[0]] = $key_pair_separated[1]; 
  }
  return $options;
}

function fetch_from_table($tablename, $alias, $compare_parameter, $parameter, $tableprimarykey)
{
    $query = db_select($tablename, $alias)
        ->fields($alias)
        ->condition($alias . '.' . $compare_parameter, $parameter);
       $result = $query->execute()
        ->fetchAll();
    if($result) return TRUE;
    else return FALSE;
}

function check_if_user_has_profile_settings($field_settings_id, $user_id)
{
    $query = db_select('iisp_field_user_data','ud')
        ->fields('ud')
        ->condition('ud.iisp_field_settings_id', $field_settings_id)
        ->condition('ud.uid', $user_id);
       $result = $query->execute()
        ->fetchObject();
    if($result) return TRUE;
    else return FALSE;
}

function get_dropdownlist($tablename, $alias, $compare_parameter, $parameter, $tableprimarykey, $parameterexpecting)
{
	
	
    $query = db_select($tablename, $alias)
        ->fields($alias)
        ->orderBy($alias . '.' . $tableprimarykey, 'DESC')
		->execute()
        ->fetchAll();
		
		
    $result = array();
    $result[''] = "- Select -";
    foreach ($query as $qry) {
        $result[$qry->$tableprimarykey] = $qry->$parameterexpecting;
    }

	
    return $result;
}

function iisp_profiler_theme() {
  return array(
    'profiler_settings_page' => array(
      'variables' => array('user_form_field_info' => NULL),      
      'template' => 'settings-page',
      'path' => drupal_get_path('module', 'iisp_profiler') .'/themes/',
      ),

    'profiler_page' => array(
      'variables' => array('user_profile_info' => NULL,'skill_categories' => NULL,'skills' => NULL,'user_profile_data_info' => NULL,'user_profile_list' => NULL),      
      'template' => 'profiler-page',
      'path' => drupal_get_path('module', 'iisp_profiler') .'/themes/',
      ),

    'profiler_dashboard_page' => array(
      'variables' => array('goals_profiler' => NULL, 'activities_profiler' => NULL),      
      'template' => 'profiler_dashboard_page',
      'path' => drupal_get_path('module', 'iisp_profiler') .'/themes/',
      ),

    'compare_page' => array(
      'variables' => array('skill_categories'=>NULL,'skills'=>NULL,'user_profile_list'=>NULL),      
      'template' => 'compare_page',
      'path' => drupal_get_path('module', 'iisp_profiler') .'/themes/',
      ),

    'profiler_page_print' => array(
      'variables' => array('compare_page' => NULL, 'activities_profiler' => NULL),      
      'template' => 'profiler_page_print',
      'path' => drupal_get_path('module', 'iisp_profiler') .'/themes/',
      )

    );

 }

 function user_system_attribute_form_fields($field_settings_id){
     global $user;
     $query = db_select('iisp_field_user_data', 'ud')
            ->fields('ud')
            ->condition('ud.uid',$user->uid)
            ->condition('ud.iisp_field_settings_id',$field_settings_id);
    $result =$query->execute()
            ->fetchObject();
    return $result;
  }

  function check_profile_skills($skill_id,$profile_id){
      $query = db_select('iisp_profile_data', 'ud')
            ->fields('ud')
            ->condition('ud.iisp_skills_id',$skill_id)
            ->condition('ud.iisp_profiles_id',$profile_id);
      $result =$query->execute()
              ->fetchObject();
      return $result;
  }
  
  function user_has_form_fields(){
     global $user;
     $query = db_select('iisp_field_user_data', 'ud')
            ->fields('ud')
            ->condition('ud.uid',$user->uid);
    $result = $query->execute()
            ->fetchObject();
    if($result) return TRUE;
    else return FALSE;
  }

 function user_goal_form_fields(){
     global $user;
     $query = db_select('iisp_goals_custom_fields', 'ud')
            ->fields('ud')
            ->condition('ud.uid',$user->uid);
    $result =$query->execute()
            ->fetchAll();
    return $result;
  }

function user_activity_form_fields(){
     global $user;
     $query = db_select('iisp_activities_custom_fields', 'ud')
            ->fields('ud')
            ->condition('ud.uid',$user->uid);
    $result =$query->execute()
            ->fetchAll();
    return $result;
  }

function get_skills_by_skill_category($skillcat_id){
    $user_skill_categories = db_select('iisp_skills', 'sc')
              ->fields('sc')
              ->condition('sc.iisp_skill_cat_id',$skillcat_id)
              ->execute()
              ->fetchAll();
    return $user_skill_categories;
}


/**
* Implements hook_permission
*/
function iisp_profiler_permission() {
  $permissions = array(
    'administer skill profiler settings' => array(
      'title' => t('Administer skill profiler module settings'),
      'description' => t('Administer skiller profiler settings mainly for administration'),
    ),
	
	'skill profiler works' => array(
      'title' => t('Skill profiler works'),
      'description' => t('Skill profiler works and permission settings'),
    ),
	
	'skiller manager works' => array(
      'title' => t('Skill manager works'),
      'description' => t('Skill manager works and permissions settings'),
    ),
  );

  return $permissions;
}

function mymodule_menu_link_alter(&$link) {

    echo "<pre>";
    print_r($link); exit;

  }
 
 
 
 function process_date($date){
	 if(!empty($date)){
      	return date("M d, Y", strtotime($date) );
	 } else {
	  	return "<span style='display:none;'>".date("M d, Y", strtotime($date) )."</span>";
	}
 }


 function get_goals_individual_data($goalid){
      $system_attribute_form_fields = db_select('iisp_goals_data', 'f')
              ->fields('f')
              ->condition('f.iisp_goals_id',$goalid)
              ->condition('f.custom', '0');
      $result = $system_attribute_form_fields->execute()->fetchALL(); 

      return $result;

 }


 function get_activities_individual_data($activityid){
     $system_attribute_form_fields = db_select('iisp_activities_data', 'f')
              ->fields('f')
              ->condition('f.iisp_activities_id',$activityid)
              ->condition('f.custom', '0');
      $result = $system_attribute_form_fields->execute()->fetchALL(); 
      
      return $result;
 }