<?php

/**
 * @file
 * IISP profiler main module.
 */

/**
 * @defgroup action_example Example: Action
 * @ingroup examples
 * @{
 * Creating actions in Drupal 7
 *
 */


/**
 * Implements hook_menu().
 *
 * Provides a menu entry which explains what the module does.
 */
function iisp_profiler_menu() {
  
  $items['admin/iisp_skills/skills/categories'] = array(
    'title'           => 'IISP skills categories',
    'description'     => 'Provides the iisp skills categories for the iisp profiler',
    'page callback'   => 'iisp_skills_categories',
  'file'            => 'admin/profiler_admin.inc', 
    'access callback' => TRUE,
  );
  
  $items['admin/iisp_skills/skills/categories/create'] = array(
    'title'           => 'create new iisp skills categories',
    'description'     => 'Provides the iisp skills categories for the iisp profiler',
    'page callback'   => 'iisp_skills_categories',
  'page arguments' => array('create'),
  'file'            => 'admin/profiler_admin.inc', 
    'access callback' => TRUE,
  );
  
  $items['admin/iisp_skills/skills/categories/%/edit'] = array(
    'title'           => 'Edit iisp skills categories',
    'description'     => 'Provides the iisp skills categories for the iisp profiler',
    'page callback'   => 'iisp_skills_categories_page_edit',
  'page arguments'  => array(4), 
  'file'            => 'admin/profiler_admin.inc', 
    'access callback' => TRUE,
  );

  $items['admin/iisp_skills/skills/subcategories'] = array(
    'title'           => 'IISP skills sub-categories',
    'description'     => 'Provides the iisp skills sub-categories for the iisp profiler',
    'page callback'   => 'iisp_skills_subcategories',
  'file'            => 'admin/profiler_admin.inc', 
    'access callback' => TRUE,
  );
  
  $items['admin/iisp_skills/skills/subcategories/create'] = array(
    'title'           => 'Create new iisp skills sub-categories',
    'description'     => 'Provides the iisp skills sub-categories for the iisp profiler',
    'page callback'   => 'iisp_skills_subcategories',
  'file'            => 'admin/profiler_admin.inc', 
    'access callback' => TRUE,
  );
  
  $items['admin/iisp_skills/skills/subcategories/%/edit'] = array(
    'title'           => 'Edit iisp skills sub-categories',
    'description'     => 'Provides the iisp skills sub-categories for the iisp profiler',
    'page callback'   => 'iisp_skills_subcategories_page_edit',
  'page arguments'  => array(4),
  'file'            => 'admin/profiler_admin.inc', 
    'access callback' => TRUE,
  );

  $items['admin/iisp_skills/skills'] = array(
    'title'           => 'IISP skills',
    'description'     => 'Provides the iisp skills for the iisp profiler',
    'page callback'   => 'iisp_skills_skills',
	'file'            => 'admin/profiler_admin_skills.inc', 
    'access callback' => TRUE,
  );
  
  $items['admin/iisp_skills/skills/create'] = array(
    'title'           => 'Create IISP skills',
    'description'     => 'Provides the iisp skills for the iisp profiler',
    'page callback'   => 'iisp_skills_skills',
	'page arguments'  => array('create'),
	'file'            => 'admin/profiler_admin_skills.inc', 
    'access callback' => TRUE,
  );
  
  $items['admin/iisp_skills/skills/%/edit'] = array(
    'title'           => 'Edit IISP skills',
    'description'     => 'Provides the iisp skills for the iisp profiler',
  'file'            => 'admin/profiler_admin.inc', 
    'page callback'   => 'iisp_skills_skills_page_edit',
	'page arguments'  => array(3),
	'file'            => 'admin/profiler_admin_skills.inc', 
    'access callback' => TRUE,
  );
  
  $items['admin/iisp_skills/config'] = array(
    'title'           => 'IISP admin configuraton',
    'description'     => 'Provides the iisp admin configuration for the iisp profiler',
    'page callback'   => 'iisp_admin_config',
  'file'            => 'admin/iisp_config.inc', 
    'access callback' => TRUE,
  );
  
  $items['admin/iisp_skills/field_settings'] = array(
    'title'           => t('Field settings'),
    'description'     => t('Provides the iisp fields settings for the iisp profiler'),
    'page callback'   => 'iisp_fields_settings',
  'file'            => 'admin/field_settings.inc', 
    'access callback' => TRUE,
  );

  $items['admin/iisp_skills/field_settings/create'] = array(
      'title' => t('Create field settings'),
      'description' => t('Create the iisp fields settings for the iisp profiler'),
      'page callback' => 'iisp_fields_settings',
      'page arguments' => array('create'),
      'access callback' => TRUE,
      'file' => 'admin/field_settings.inc',
      'weight' => 1,
  );


  $items['admin/iisp_skills/field_settings/%/edit'] = array(
      'title' => t('Edit field settings'),
      'description' => t('Edit the iisp fields settings for the iisp profiler'),
      'page callback' => 'iisp_fields_settings_page_edit',
      'page arguments' => array(3),
      'access callback' => TRUE,
      'file' => 'admin/field_settings.inc',
      'weight' => 1,
  );

  $items['iisp_skills/settings'] = array(
    'title'           => 'Settings',
    'description'     => 'Provides the settings for the iisp profiler',
    'page callback'   => 'iisp_profiler_settings',
	'file'            => 'profiler_settings.inc', 
    'access callback' => TRUE,
  );
  
  $items['admin/iisp_skills/sifa_skills_types'] = array(
    'title'           => 'SIfA skills types',
    'description'     => 'Provides the SIFA skills types',
    'page callback'   => 'sifa_skill_types',
	'file'            => 'admin/sifa_skill_types_settings.inc', 
    'access callback' => TRUE,
  );

  $items['admin/iisp_skills/sifa_skills_levels'] = array(
    'title'           => 'SIfA skills levels',
    'description'     => 'Provides the SIFA skills levels',
    'page callback'   => 'sifa_skill_levels',
    'file'            => 'admin/sifa_skill_levels_settings.inc', 
    'access callback' => TRUE,
  );
  
  $items['iisp_skills/activities'] = array(
    'title'           => 'Activities',
    'description'     => 'Provides the activities for the iisp profiler',
    'page callback'   => 'iisp_profiler_activities',
  'file'            => 'profiler_activities.inc', 
    'access callback' => TRUE,
  );
  
  $items['iisp_skills/goals'] = array(
    'title'           => 'Goals',
    'description'     => 'Provides the goals for the iisp profiler',
    'page callback'   => 'iisp_profiler_goals',
  'file'            => 'profiler_goals.inc', 
    'access callback' => TRUE,
  );
  
  $items['iisp_skills/profiles'] = array(
    'title'           => 'Profiles',
    'description'     => 'Provides the profiles for the iisp profiler',
    'page callback'   => 'iisp_profiler',
	'file'            => 'profiler_goals.inc', 
    'access callback' => TRUE,
  );
  
  $items['iisp_skills/dashboard'] = array(
    'title'           => 'Dashboard',
    'description'     => 'Provides the dashboard for the iisp profiler',
    'page callback'   => 'iisp_profiler_dashboard',
  'file'            => 'profiler_dashboard.inc', 
    'access callback' => TRUE,
  );

  $items['iisp_skills/ajax_settings'] = array(
    'title'           => 'Settings',
    'description'     => 'Provides the ajax callback settings for the iisp profiler',
    'page callback'   => 'ajax_settings',
    'file'            => 'profiler_settings.inc', 
    'access callback' => TRUE,
  );
  
  
  return $items;
  
}

global $base_url;

  $path = 'sites/all/modules/iisp_profiler';
        drupal_add_css($base_url . '/' . $path . '/css/custom-style.css', array('type' => 'file', 'scope' => 'footer', 'weight' => 20));


//Custom functions
function get_active_variable($act) {
   if($act == '1') {
       $active = "Yes";
   } else {
       $active = "No" ;
   }    

   return $active;
}

function get_keyvalue_array($keyvalue_unmanaged_arr){
  $options = array();
    $keyvalue_unmanaged_arr = preg_split("/\\r\\n|\\r|\\n/", $keyvalue_unmanaged_arr);
  foreach($keyvalue_unmanaged_arr as $kpr){
    $key_pair_separated = explode('|', $kpr);
    $options[$key_pair_separated[0]] = $key_pair_separated[1]; 
  }
  return $options;
}

function fetch_from_table($tablename, $alias, $compare_parameter, $parameter, $tableprimarykey)
{
    $query = db_select($tablename, $alias)
        ->fields($alias)
        ->condition($alias . '.' . $compare_parameter, $parameter);
       $result = $query->execute()
        ->fetchAll();
    if($result) return TRUE;
    else return FALSE;
}

function check_if_user_has_profile_settings($field_settings_id, $user_id)
{
    $query = db_select('iisp_field_user_data','ud')
        ->fields('ud')
        ->condition('ud.iisp_field_settings_id', $field_settings_id)
        ->condition('ud.uid', $user_id);
       $result = $query->execute()
        ->fetchObject();
    if($result) return TRUE;
    else return FALSE;
}

function get_dropdownlist($tablename, $alias, $compare_parameter, $parameter, $tableprimarykey, $parameterexpecting)
{
	
	
    $query = db_select($tablename, $alias)
        ->fields($alias)
        ->orderBy($alias . '.' . $tableprimarykey, 'DESC')
		->execute()
        ->fetchAll();
		
		
    $result = array();
    $result[''] = "- Select -";
    foreach ($query as $qry) {
        $result[$qry->$tableprimarykey] = $qry->$parameterexpecting;
    }

	
    return $result;
}



